"""add supplier_id to products

Revision ID: 8b75ff5e5f40
Revises: edcbcda6dad3
Create Date: 2026-01-02 14:35:11.473532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b75ff5e5f40'
down_revision: Union[str, Sequence[str], None] = 'edcbcda6dad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'products', 'suppliers', ['supplier_id'], ['id'])
    op.create_unique_constraint(None, 'suppliers', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'suppliers', type_='unique')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'supplier_id')
    # ### end Alembic commands ###
